# conda env create -f environment.yml
name: desihigh
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - wget 
  - numpy
  - matplotlib
  - pandas
  - astropy
  - scipy
  - fitsio
  - papermill
  - jupyter
  - sparclclient
